#pragma once

#ifndef RENDERBUFFER_H
#define RENDERBUFFER_H

namespace loki
{

namespace graphics
{

class RenderBuffer
{
public:
	enum EInternalFormat
	{
		INTERNAL_FORMAT_DEPTH_COMPONENT = 0,
		INTERNAL_FORMAT_DEPTH_COMPONENT16,
		INTERNAL_FORMAT_DEPTH_COMPONENT24,
		INTERNAL_FORMAT_DEPTH_COMPONENT32,
		INTERNAL_FORMAT_DEPTH_STENCIL,
		INTERNAL_FORMAT_DEPTH24_STENCIL8,
		INTERNAL_FORMAT_LUMINANCE,
		INTERNAL_FORMAT_LUMINANCE4,
		INTERNAL_FORMAT_LUMINANCE8,
		INTERNAL_FORMAT_LUMINANCE12,
		INTERNAL_FORMAT_LUMINANCE16,
		INTERNAL_FORMAT_LUMINANCE_ALPHA,
		INTERNAL_FORMAT_LUMINANCE4_ALPHA4,
		INTERNAL_FORMAT_LUMINANCE6_ALPHA2,
		INTERNAL_FORMAT_LUMINANCE8_ALPHA8,
		INTERNAL_FORMAT_LUMINANCE12_ALPHA4,
		INTERNAL_FORMAT_LUMINANCE12_ALPHA12,
		INTERNAL_FORMAT_LUMINANCE16_ALPHA16,
		INTERNAL_FORMAT_INTENSITY,
		INTERNAL_FORMAT_INTENSITY4,
		INTERNAL_FORMAT_INTENSITY8,
		INTERNAL_FORMAT_INTENSITY12,
		INTERNAL_FORMAT_INTENSITY16,
		INTERNAL_FORMAT_R3_G3_B2,
		INTERNAL_FORMAT_RGB,
		INTERNAL_FORMAT_RGB4,
		INTERNAL_FORMAT_RGB5,
		INTERNAL_FORMAT_RGB8,
		INTERNAL_FORMAT_RGB10,
		INTERNAL_FORMAT_RGB12,
		INTERNAL_FORMAT_RGB16,
		INTERNAL_FORMAT_RGB32F,
		INTERNAL_FORMAT_RGBA,
		INTERNAL_FORMAT_RGBA2,
		INTERNAL_FORMAT_RGBA4,
		INTERNAL_FORMAT_RGB5_A1,
		INTERNAL_FORMAT_RGBA8,
		INTERNAL_FORMAT_RGB10_A2,
		INTERNAL_FORMAT_RGBA12,
		INTERNAL_FORMAT_RGBA16,
		INTERNAL_FORMAT_RGBA32F,

		_INTERNAL_FORMAT_COUNT
	};

	~RenderBuffer();

	static RenderBuffer* Create( EInternalFormat _InternalFormat, int32 _Width, int32 _Height );

	uint32 GetBufferHandle() const;

	void Bind() const;
	void Unbind() const;

private:
	RenderBuffer( EInternalFormat _InternalFormat, int32 _Width, int32 _Height );
	RenderBuffer();

	uint32 m_GLBufferHandle;
	EInternalFormat m_InternalFormat;
	int32 m_Width;
	int32 m_Height;
};

}

}

#endif