#pragma once

#ifndef RENDERER_ENUMS_H
#define RENDERER_ENUMS_H

#include <GLEW\\glew.h>

//#define USE_EXT_DEPTH_STENCIL	// If defined, certain OpenGL defined preprocessor defines will have _EXT appended to them in order to use 
								// the extension version instead of core.
								// Example: RBIF_DEPTH_STENCIL is defined to GL_DEPTH_STENCIL without USE_EXT_DEPTH_STENCIL, but it's defined
								// to GL_DEPTH_STENCIL_EXT *with* USE_EXT_DEPTH_STENCIL.

#ifdef USE_EXT_DEPTH_STENCIL
#define EXT(v)	v##_EXT
#else
#define EXT(v)	v
#endif

namespace loki
{

namespace renderer
{

enum EInternalFormat
{
	RBIF_DEPTH_COMPONENT		= GL_DEPTH_COMPONENT, 
	RBIF_DEPTH_COMPONENT16		= GL_DEPTH_COMPONENT16, 
	RBIF_DEPTH_COMPONENT24		= GL_DEPTH_COMPONENT24, 
	RBIF_DEPTH_COMPONENT32		= GL_DEPTH_COMPONENT32,
	RBIF_DEPTH_STENCIL			= EXT(GL_DEPTH_STENCIL),
	RBIF_DEPTH24_STENCIL8		= EXT(GL_DEPTH24_STENCIL8),
	RBIF_LUMINANCE				= GL_LUMINANCE, 
	RBIF_LUMINANCE4				= GL_LUMINANCE4, 
	RBIF_LUMINANCE8				= GL_LUMINANCE8, 
	RBIF_LUMINANCE12			= GL_LUMINANCE12, 
	RBIF_LUMINANCE16			= GL_LUMINANCE16, 
	RBIF_LUMINANCE_ALPHA		= GL_LUMINANCE_ALPHA, 
	RBIF_LUMINANCE4_ALPHA4		= GL_LUMINANCE4_ALPHA4, 
	RBIF_LUMINANCE6_ALPHA2		= GL_LUMINANCE6_ALPHA2, 
	RBIF_LUMINANCE8_ALPHA8		= GL_LUMINANCE8_ALPHA8, 
	RBIF_LUMINANCE12_ALPHA4		= GL_LUMINANCE12_ALPHA4, 
	RBIF_LUMINANCE12_ALPHA12	= GL_LUMINANCE12_ALPHA12, 
	RBIF_LUMINANCE16_ALPHA16	= GL_LUMINANCE16_ALPHA16, 
	RBIF_INTENSITY				= GL_INTENSITY, 
	RBIF_INTENSITY4				= GL_INTENSITY4, 
	RBIF_INTENSITY8				= GL_INTENSITY8, 
	RBIF_INTENSITY12			= GL_INTENSITY12, 
	RBIF_INTENSITY16			= GL_INTENSITY16,
	RBIF_R3_G3_B2				= GL_R3_G3_B2,
	RBIF_RGB					= GL_RGB,
	RBIF_RGB4					= GL_RGB4,
	RBIF_RGB5					= GL_RGB5,
	RBIF_RGB8					= GL_RGB8,
	RBIF_RGB10					= GL_RGB10,
	RBIF_RGB12					= GL_RGB12,
	RBIF_RGB16					= GL_RGB16,
	RBIF_RGB32F					= GL_RGB32F,
	RBIF_RGBA					= GL_RGBA,
	RBIF_RGBA2					= GL_RGBA2,
	RBIF_RGBA4					= GL_RGBA4,
	RBIF_RGB5_A1				= GL_RGB5_A1,
	RBIF_RGBA8					= GL_RGBA8,
	RBIF_RGB10_A2				= GL_RGB10_A2,
	RBIF_RGBA12					= GL_RGBA12,
	RBIF_RGBA16					= GL_RGBA16,
	RBIF_RGBA32F				= GL_RGBA32F
};

enum ETextureFormat
{
	RBF_COLOR_INDEX		= GL_COLOR_INDEX,
	RBF_RED				= GL_RED,
	RBF_GREEN			= GL_GREEN,
	RBF_BLUE			= GL_BLUE,
	RBF_ALPHA			= GL_ALPHA,
	RBF_RGB				= GL_RGB,
	RBF_BGR				= GL_BGR,
	RBF_RGBA			= GL_RGBA,
	RBF_BGRA			= GL_BGRA,
	RBF_LUMINANCE		= GL_LUMINANCE,
	RBF_LUMINANCE_ALPHA = GL_LUMINANCE_ALPHA,
	RBF_DEPTH_STENCIL	= EXT(GL_DEPTH_STENCIL)
};

enum ETextureType
{
	RBT_UNSIGNED_BYTE				= GL_UNSIGNED_BYTE, 
	RBT_BYTE						= GL_BYTE, 
	RBT_BITMAP						= GL_BITMAP, 
	RBT_UNSIGNED_SHORT				= GL_UNSIGNED_SHORT, 
	RBT_SHORT						= GL_SHORT, 
	RBT_UNSIGNED_INT				= GL_UNSIGNED_INT, 
	RBT_INT							= GL_INT, 
	RBT_FLOAT						= GL_FLOAT, 
	RBT_UNSIGNED_BYTE_3_3_2			= GL_UNSIGNED_BYTE_3_3_2, 
	RBT_UNSIGNED_BYTE_2_3_3_REV		= GL_UNSIGNED_BYTE_2_3_3_REV, 
	RBT_UNSIGNED_SHORT_5_6_5		= GL_UNSIGNED_SHORT_5_6_5, 
	RBT_UNSIGNED_SHORT_5_6_5_REV	= GL_UNSIGNED_SHORT_5_6_5_REV, 
	RBT_UNSIGNED_SHORT_4_4_4_4		= GL_UNSIGNED_SHORT_4_4_4_4, 
	RBT_UNSIGNED_SHORT_4_4_4_4_REV	= GL_UNSIGNED_SHORT_4_4_4_4_REV, 
	RBT_UNSIGNED_SHORT_5_5_5_1		= GL_UNSIGNED_SHORT_5_5_5_1, 
	RBT_UNSIGNED_SHORT_1_5_5_5_REV	= GL_UNSIGNED_SHORT_1_5_5_5_REV, 
	RBT_UNSIGNED_INT_8_8_8_8		= GL_UNSIGNED_INT_8_8_8_8, 
	RBT_UNSIGNED_INT_8_8_8_8_REV	= GL_UNSIGNED_INT_8_8_8_8_REV, 
	RBT_UNSIGNED_INT_10_10_10_2		= GL_UNSIGNED_INT_10_10_10_2, 
	RBT_UNSIGNED_INT_2_10_10_10_REV = GL_UNSIGNED_INT_2_10_10_10_REV,
	RBT_UNSIGNED_INT_24_8			= EXT(GL_UNSIGNED_INT_24_8)
};

enum EAttachment
{
	RBA_COLOR_ATTACHMENT0			= GL_COLOR_ATTACHMENT0,
	RBA_COLOR_ATTACHMENT1			= GL_COLOR_ATTACHMENT1,
	RBA_COLOR_ATTACHMENT2			= GL_COLOR_ATTACHMENT2,
	RBA_COLOR_ATTACHMENT3			= GL_COLOR_ATTACHMENT3,
	RBA_COLOR_ATTACHMENT4			= GL_COLOR_ATTACHMENT4,
	RBA_COLOR_ATTACHMENT5			= GL_COLOR_ATTACHMENT5,
	RBA_COLOR_ATTACHMENT6			= GL_COLOR_ATTACHMENT6,
	RBA_COLOR_ATTACHMENT7			= GL_COLOR_ATTACHMENT7,
	RBA_COLOR_ATTACHMENT8			= GL_COLOR_ATTACHMENT8,
	RBA_COLOR_ATTACHMENT9			= GL_COLOR_ATTACHMENT9,
	RBA_COLOR_ATTACHMENT10			= GL_COLOR_ATTACHMENT10,
	RBA_COLOR_ATTACHMENT11			= GL_COLOR_ATTACHMENT11,
	RBA_COLOR_ATTACHMENT12			= GL_COLOR_ATTACHMENT12,
	RBA_COLOR_ATTACHMENT13			= GL_COLOR_ATTACHMENT13,
	RBA_COLOR_ATTACHMENT14			= GL_COLOR_ATTACHMENT14,
	RBA_COLOR_ATTACHMENT15			= GL_COLOR_ATTACHMENT15,
	RBA_DEPTH_ATTACHMENT			= GL_DEPTH_ATTACHMENT,
	RBA_STENCIL_ATTACHMENT			= GL_STENCIL_ATTACHMENT,
	RBA_DEPTH_STENCIL_ATTACHMENT	= GL_DEPTH_STENCIL_ATTACHMENT
};

}

}

#ifdef EXT
#undef EXT
#endif

#endif