# Comments can either start with a pound character
; or with a semicolon.
[section]
thisisaname=aproperty
secondname =prop
testingagain = 23

[abcdef]
b = 1
a = 2

[section2]
andwhataboutTHIS = what
propertynamewithnumber3 = 192.168.0.0.1