#pragma once

#ifndef ENUMS_H
#define ENUMS_H

namespace loki
{

namespace graphics
{

// Cg input semantic names and values. The comment on each line provides the semantic name as it should appear in the
// Cg shader. Each value is simply the index to which Cg binds a semantic and can be used
// in the C++ application code to bind data to locations.
enum ECgSemantics
{
	ATTR0 = 0,		POSITION = 0,
	ATTR1 = 1,		BLENDWEIGHT = 1,
	ATTR2 = 2,		NORMAL = 2,
	ATTR3 = 3,		COLOR0 = 3,			DIFFUSE = 3,
	ATTR4 = 4,		COLOR1 = 4,			SPECULAR = 4,
	ATTR5 = 5,		FOGCOORD = 5,		TESSFACTOR = 5,
	ATTR6 = 6,		POINTSIZE = 6,		// NOTE: Cg shader semantic for point size is actually 'PSIZE', but can't be used here because it's typedeffed.
	ATTR7 = 7,		BLENDINDICES = 7,
	ATTR8 = 8,		TEXCOORD0 = 8,
	ATTR9 = 9,		TEXCOORD1 = 9,
	ATTR10 = 10,	TEXCOORD2 = 10,
	ATTR11 = 11,	TEXCOORD3 = 11,
	ATTR12 = 12,	TEXCOORD4 = 12,
	ATTR13 = 13,	TEXCOORD5 = 13,
	ATTR14 = 14,	TEXCOORD6 = 14,		TANGENT = 14,
	ATTR15 = 15,	TEXCOORD7 = 15,		BINORMAL = 15
};

enum EInternalFormat
{
	INTERNAL_FORMAT_DEPTH_COMPONENT = 0,
	INTERNAL_FORMAT_DEPTH_COMPONENT16,
	INTERNAL_FORMAT_DEPTH_COMPONENT24,
	INTERNAL_FORMAT_DEPTH_COMPONENT32,
	INTERNAL_FORMAT_DEPTH_STENCIL,
	INTERNAL_FORMAT_DEPTH24_STENCIL8,
	INTERNAL_FORMAT_LUMINANCE,
	INTERNAL_FORMAT_LUMINANCE4,
	INTERNAL_FORMAT_LUMINANCE8,
	INTERNAL_FORMAT_LUMINANCE12,
	INTERNAL_FORMAT_LUMINANCE16,
	INTERNAL_FORMAT_LUMINANCE_ALPHA,
	INTERNAL_FORMAT_LUMINANCE4_ALPHA4,
	INTERNAL_FORMAT_LUMINANCE6_ALPHA2,
	INTERNAL_FORMAT_LUMINANCE8_ALPHA8,
	INTERNAL_FORMAT_LUMINANCE12_ALPHA4,
	INTERNAL_FORMAT_LUMINANCE12_ALPHA12,
	INTERNAL_FORMAT_LUMINANCE16_ALPHA16,
	INTERNAL_FORMAT_INTENSITY,
	INTERNAL_FORMAT_INTENSITY4,
	INTERNAL_FORMAT_INTENSITY8,
	INTERNAL_FORMAT_INTENSITY12,
	INTERNAL_FORMAT_INTENSITY16,
	INTERNAL_FORMAT_R3_G3_B2,
	INTERNAL_FORMAT_RGB,
	INTERNAL_FORMAT_RGB4,
	INTERNAL_FORMAT_RGB5,
	INTERNAL_FORMAT_RGB8,
	INTERNAL_FORMAT_RGB10,
	INTERNAL_FORMAT_RGB12,
	INTERNAL_FORMAT_RGB16,
	INTERNAL_FORMAT_RGB32F,
	INTERNAL_FORMAT_RGBA,
	INTERNAL_FORMAT_RGBA2,
	INTERNAL_FORMAT_RGBA4,
	INTERNAL_FORMAT_RGB5_A1,
	INTERNAL_FORMAT_RGBA8,
	INTERNAL_FORMAT_RGB10_A2,
	INTERNAL_FORMAT_RGBA12,
	INTERNAL_FORMAT_RGBA16,
	INTERNAL_FORMAT_RGBA32F,

	_INTERNAL_FORMAT_COUNT
};

enum ETextureFormat
{
	TEXTURE_FORMAT_COLOR_INDEX = 0,
	TEXTURE_FORMAT_RED,
	TEXTURE_FORMAT_GREEN,
	TEXTURE_FORMAT_BLUE,
	TEXTURE_FORMAT_ALPHA,
	TEXTURE_FORMAT_RGB,
	TEXTURE_FORMAT_BGR,
	TEXTURE_FORMAT_RGBA,
	TEXTURE_FORMAT_BGRA,
	TEXTURE_FORMAT_LUMINANCE,
	TEXTURE_FORMAT_LUMINANCE_ALPHA,
	TEXTURE_FORMAT_DEPTH_STENCIL,

	_TEXTURE_FORMAT_COUNT
};

enum ETextureType
{
	TEXTURE_TYPE_UNSIGNED_BYTE = 0,
	TEXTURE_TYPE_BYTE,
	TEXTURE_TYPE_BITMAP,
	TEXTURE_TYPE_UNSIGNED_SHORT,
	TEXTURE_TYPE_SHORT,
	TEXTURE_TYPE_UNSIGNED_INT,
	TEXTURE_TYPE_INT,
	TEXTURE_TYPE_FLOAT,
	TEXTURE_TYPE_UNSIGNED_BYTE_3_3_2,
	TEXTURE_TYPE_UNSIGNED_BYTE_2_3_3_REV,
	TEXTURE_TYPE_UNSIGNED_SHORT_5_6_5,
	TEXTURE_TYPE_UNSIGNED_SHORT_5_6_5_REV,
	TEXTURE_TYPE_UNSIGNED_SHORT_4_4_4_4,
	TEXTURE_TYPE_UNSIGNED_SHORT_4_4_4_4_REV,
	TEXTURE_TYPE_UNSIGNED_SHORT_5_5_5_1,
	TEXTURE_TYPE_UNSIGNED_SHORT_1_5_5_5_REV,
	TEXTURE_TYPE_UNSIGNED_INT_8_8_8_8,
	TEXTURE_TYPE_UNSIGNED_INT_8_8_8_8_REV,
	TEXTURE_TYPE_UNSIGNED_INT_10_10_10_2,
	TEXTURE_TYPE_UNSIGNED_INT_2_10_10_10_REV,
	TEXTURE_TYPE_UNSIGNED_INT_24_8,

	_TEXTURE_TYPE_COUNT
};

enum EFrameBufferAttachment
{
	FRAMEBUFFER_COLOR_ATTACHMENT0 = 0,
	FRAMEBUFFER_COLOR_ATTACHMENT1,
	FRAMEBUFFER_COLOR_ATTACHMENT2,
	FRAMEBUFFER_COLOR_ATTACHMENT3,
	FRAMEBUFFER_COLOR_ATTACHMENT4,
	FRAMEBUFFER_COLOR_ATTACHMENT5,
	FRAMEBUFFER_COLOR_ATTACHMENT6,
	FRAMEBUFFER_COLOR_ATTACHMENT7,
	FRAMEBUFFER_COLOR_ATTACHMENT8,
	FRAMEBUFFER_COLOR_ATTACHMENT9,
	FRAMEBUFFER_COLOR_ATTACHMENT10,
	FRAMEBUFFER_COLOR_ATTACHMENT11,
	FRAMEBUFFER_COLOR_ATTACHMENT12,
	FRAMEBUFFER_COLOR_ATTACHMENT13,
	FRAMEBUFFER_COLOR_ATTACHMENT14,
	FRAMEBUFFER_COLOR_ATTACHMENT15,
	FRAMEBUFFER_DEPTH_ATTACHMENT,
	FRAMEBUFFER_STENCIL_ATTACHMENT,
	FRAMEBUFFER_DEPTH_STENCIL_ATTACHMENT,

	_FRAMEBUFFER_ATTACHMENT_COUNT
};

enum ETextureParameterName
{
	TEXTURE_WRAP_S = 0,
	TEXTURE_WRAP_T,
	TEXTURE_MIN_FILTER,
	TEXTURE_MAG_FILTER,
	TEXTURE_PRIORITY,
	TEXTURE_BORDER_COLOR,

	_TEXTURE_PARAMETER_NAME_COUNT
};

enum ETextureParameterValue
{
	REPEAT = 0,
	CLAMP,
	CLAMP_TO_EDGE,
	NEAREST,
	LINEAR,
	NEAREST_MIPMAP_NEAREST,
	LINEAR_MIPMAP_NEAREST,
	NEAREST_MIPMAP_LINEAR,
	LINEAR_MIPMAP_LINEAR,

	_TEXTURE_PARAMETER_VALUE_COUNT
};

extern uint32 GLInternalFormats[];
extern uint32 GLTextureFormats[];
extern uint32 GLTextureTypes[];
extern uint32 GLFrameBufferAttachments[];
extern uint32 GLTextureParameterNames[];
extern uint32 GLTextureParameterValues[];

EInternalFormat GetEnumInteralFormat( uint32 _GLEnum );
ETextureFormat GetEnumTextureFormat( uint32 _GLEnum );
ETextureType GetEnumTextureType( uint32 _GLEnum );
EFrameBufferAttachment GetEnumFrameBufferAttachment( uint32 _GLEnum );
ETextureParameterName GetEnumTextureParameterName( uint32 _GLEnum );
ETextureParameterValue GetEnumTextureParameterValue( uint32 _GLEnum );

}

}

#endif